paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Los productos fueron obtenidos satisfactoriamente
        '500':
          description: Error interno del servidor
    post:
      summary: Crea un producto
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: El producto fue creado satisfactoriamente
        '500':
          description: Error interno del servidor
  /api/products/{id}:
    get:
      summary: Obtiene un producto por id
      tags:
        - Products
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id del producto
      responses:
        '200':
          description: El producto fue obtenido satisfactoriamente
        '404':
          description: El producto no existe
        '500':
          description: Error interno del servidor
    put:
      summary: Actualiza un producto por id
      tags:
        - Products
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id del producto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: El producto fue actualizado satisfactoriamente
        '404':
          description: El producto no existe
        '500':
          description: Error interno del servidor
    delete:
      summary: Elimina un producto por id
      tags:
        - Products
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id del producto
      responses:
        '200':
          description: El producto fue eliminado satisfactoriamente
        '404':
          description: El producto no existe
        '500':
          description: Error interno del servidor


components:
  schemas:
    Product:
      type: object
      properties:
        _pid:
          type: ObjectId
          description: Id autogenerado de mongo
        name:
          type: String
          description: Nombre del producto
        brand:
          type: String
          description: Marca del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock del producto
        thumbnail:
          type: String
          description: Foto del producto
        category:
          type: String
          description: Categoría del producto
        subcategory:
          type: String
          description: Subcategoría del producto
        description:
          type: String
          description: Descripción del producto
        active:
          type: Boolean
          description: Estado del producto